//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBibliaMergeTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iBibliaMergeTool.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You have to select a destination project first!.
        /// </summary>
        internal static string ChooseADestinationProject {
            get {
                return ResourceManager.GetString("ChooseADestinationProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You have to enter a filter first!.
        /// </summary>
        internal static string ChooseAFilter {
            get {
                return ResourceManager.GetString("ChooseAFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You have to select a source project first!.
        /// </summary>
        internal static string ChooseASourceProject {
            get {
                return ResourceManager.GetString("ChooseASourceProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You have to choose at least one field to be copied..
        /// </summary>
        internal static string ChooseAtLeatOneField {
            get {
                return ResourceManager.GetString("ChooseAtLeatOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your filter doesn&apos;t match any verse. Please try again..
        /// </summary>
        internal static string EmptyFilterResults {
            get {
                return ResourceManager.GetString("EmptyFilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge completed successfully!.
        /// </summary>
        internal static string MergeComplete {
            get {
                return ResourceManager.GetString("MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error, merge process aborted: .
        /// </summary>
        internal static string MergeError {
            get {
                return ResourceManager.GetString("MergeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error, you filter doesn&apos;t seem to be valid: .
        /// </summary>
        internal static string UnexpectedFilterError {
            get {
                return ResourceManager.GetString("UnexpectedFilterError", resourceCulture);
            }
        }
    }
}
